apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-rental
spec:
  selector:
    matchLabels:
      app: library-rental
  replicas: 2
  template:
    metadata:
      labels:
        app: library-rental
    spec:
      containers:
      - name: library-rental
        image: yurizp/library
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: library-rental-secret
