apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: library-rental-ingress
spec:
  tls:
    - hosts:
      - yurizp.com
      secretName: tls-secret
  rules:
  - host: library-rental.yurizp.com
    http:
      paths:
      - backend:
          serviceName: library-rental
          servicePort: 80